CELL_SIZE = 30
PLAYFIELD_W = 10
PLAYFIELD_H = 20
PANEL_WIDTH = 6
MARGIN = 20
PADDING = 8

FIELD_PIX_W = PLAYFIELD_W * CELL_SIZE
FIELD_PIX_H = PLAYFIELD_H * CELL_SIZE
INFO_PIX_W = PANEL_WIDTH * CELL_SIZE
WINDOW_W = MARGIN + (FIELD_PIX_W + INFO_PIX_W + MARGIN) * 2
WINDOW_H = MARGIN*2 + FIELD_PIX_H 